name: gerry
channels:
    - conda-forge
      #    - ostrokach-forge
      #    - pkgw-forge
dependencies:
    - python=3.6
    - jupyter
    - numpy
    - scipy
    - matplotlib
    - basemap
    - pandas
    - conda-forge::geopandas
    - conda-forge::geoplot
    - shapely
    - conda-forge::gdal
      #    - gtk3
      #    - pygobject
      #    - graph-tool
    - conda-forge::fiona=1.6.0
